#!/usr/bin/env bash

# Execute MRTG to build a history     
#mrtg mrtg.cfg
#   environment:
#     LD_PRELOAD=/usr/local/lib/libfaketime.so.1 FAKETIME="-15d"
# See https://github.com/wolfcw/libfaketime
lxc exec mrtg-v1 -- faketime -15d date
lxc exec mrtg-v1 -- faketime -15d "perl -MPOSIX -le 'print strftime "%F", localtime'"
