---
- name: install MRTG v1.0
  hosts: mrtgservers
  remote_user: root

  tasks:
  - name: install mrtg v1.0
    unarchive:
      src: https://github.com/oetiker/mrtg/archive/1.0.tar.gz
      dest: /root
      remote_src: yes

  - name: install fake snmpget
    copy:
      src: "{{ playbook_dir }}/snmpget"
      dest: /usr/local/bin
      mode: u+rwx,g+rx,o+rx

  - name: install dependencies
    apt:
      pkg:
      - netpbm
      - faketime
      state: present

  - name: create output directory
    file:
      path: /root/output
      state: directory

  - name: create fake mib
    file:
      path: /root/fakemib.txt
      state: touch

  - name: fix mrtg shebang
    lineinfile:
      path: /root/mrtg-1.0/mrtg
      regexp: '#!/usr/local/bin/perl5'
      line: "#!/usr/bin/perl"

  - name: update WorkDir in mrtg config
    lineinfile:
      path: /root/mrtg-1.0/mrtg.cfg
      regexp: '^WorkDir:'
      line: "WorkDir: /root/output"

  - name: update snmpget in mrtg config
    lineinfile:
      path: /root/mrtg-1.0/mrtg.cfg
      regexp: '^snmpget:'
      line: "snmpget: /usr/local/bin/snmpget"

  - name: update ppmtogif in mrtg config
    lineinfile:
      path: /root/mrtg-1.0/mrtg.cfg
      regexp: '^ppmtogif:'
      line: "ppmtogif: /usr/bin/ppmtogif"

  - name: update mibfile in mrtg config
    lineinfile:
      path: /root/mrtg-1.0/mrtg.cfg
      regexp: '^mibfile:'
      line: "mibfile: /root/fakemib.txt"
 